# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - CATKIN_PARALLEL_JOBS='-p2'
    - CATKIN_PARALLEL_TEST_JOBS='-p1'
    - ROS_PARALLEL_JOBS="-j2"
    - ROS_PARALLEL_TEST_JOBS='-j1'
  matrix:
    - ROS_DISTRO=indigo  USE_DEB=true
    - ROS_DISTRO=indigo  USE_DEB=false NOT_TEST_INSTALL=true
    - ROS_DISTRO=kinetic USE_DEB=false
    - ROS_DISTRO=melodic USE_DEB=false
matrix:
  # allow_failures:
  #   - env: ROS_DISTRO=indigo  USE_DEB=false NOT_TEST_INSTALL=true
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
      - youhei@jsk.t.u-tokyo.ac.jp
      - ueda@jsk.t.u-tokyo.ac.jp
      - noazawa@jsk.t.u-tokyo.ac.jp
      - iiysaito@opensource-robotics.tokyo.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_script:
  # rtmros_gazebo/hrpsys_gazebo_atlas is tested here, because tests for hrpsys_gazebo_atlas depend on rtmros_tutorials/hrpsys_ros_bridge_tutorials.
  - export TEST_PKGS="`catkin_topological_order ${CI_SOURCE_PATH} --only-names` hrpsys_gazebo_atlas"
script: source .travis/travis.sh
