# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - CATKIN_PARALLEL_JOBS='-p2'
    - CATKIN_PARALLEL_TEST_JOBS='-p1'
    - ROS_PARALLEL_JOBS="-j2"
    - ROS_PARALLEL_TEST_JOBS='-j1'
  matrix:
    - ROS_DISTRO=indigo  USE_DEB=true
    - ROS_DISTRO=indigo  USE_DEB=false NOT_TEST_INSTALL=true
    # rtmros_gazebo/hrpsys_gazebo_atlas is tested here, because tests for hrpsys_gazebo_atlas depend on rtmros_tutorials/hrpsys_ros_bridge_tutorials.
    - ROS_DISTRO=indigo  USE_DEB=false NOT_TEST_INSTALL=true INSTALL_SRC="https://github.com/start-jsk/rtmros_gazebo.git" ADDITIONAL_TEST_PKGS="hrpsys_gazebo_atlas"
    - ROS_DISTRO=kinetic USE_DEB=false ADDITIONAL_TEST_PKGS="hrpsys_gazebo_atlas"
matrix:
  # allow_failures:
  #   - env: ROS_DISTRO=indigo  USE_DEB=false NOT_TEST_INSTALL=true
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
      - youhei@jsk.t.u-tokyo.ac.jp
      - ueda@jsk.t.u-tokyo.ac.jp
      - noazawa@jsk.t.u-tokyo.ac.jp
      - iiysaito@opensource-robotics.tokyo.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_script:
  - if [ "${INSTALL_SRC}" != "" ]; then export BEFORE_SCRIPT="sudo apt-get install python-yaml; $(for src in $INSTALL_SRC; do name=`basename $src`; echo "python -c \"import yaml;print yaml.dump([{\\\"git\\\":{\\\"uri\\\":\\\"$src\\\",\\\"local-name\\\":\\\"$name\\\"}}], default_flow_style=False)\" >> .rosinstall;"; done) ls -al; cat .rosinstall; wstool update"; fi
  - if [ "${ADDITIONAL_TEST_PKGS}" != "" ] && [ "${TEST_PKGS}" == "" ] ; then export TEST_PKGS="`catkin_topological_order ${CI_SOURCE_PATH} --only-names` ${ADDITIONAL_TEST_PKGS}"; fi
script: source .travis/travis.sh
